# ============================================================
# PAGE 2 — REGION-BASED FORECAST
# ============================================================

elif page == "📍 Region-Based Forecast":

    st.title(
        "📍 Region-Based Forecast"
    )

    st.caption(
        "View the region-level forecast generated by the "
        "Final Trial 84 Log-XGBoost model."
    )

    if region_forecast_df.empty:

        st.error(
            "new_region_forecast.csv "
            "could not be loaded."
        )

    else:

        required = [
            "Forecast_Date",
            "Product_ID",
            "Product_Name",
            "Predicted_Units_Sold"
        ]

        missing = [
            c
            for c in required
            if c not in region_forecast_df.columns
        ]

        if missing:

            st.error(
                f"Missing columns in region forecast CSV: {missing}"
            )

            st.write(
                "Columns found:",
                list(region_forecast_df.columns)
            )

        else:

            region_data = (
                region_forecast_df.copy()
            )

            region_data["Forecast_Date"] = pd.to_datetime(
                region_data["Forecast_Date"],
                errors="coerce"
            )

            region_data["Predicted_Units_Sold"] = (
                pd.to_numeric(
                    region_data[
                        "Predicted_Units_Sold"
                    ],
                    errors="coerce"
                )
                .fillna(0)
                .clip(lower=0)
                .round()
                .astype(int)
            )

            region_data = region_data.dropna(
                subset=["Forecast_Date"]
            )

            c1, c2 = st.columns(2)

            with c1:

                current_date = st.date_input(
                    "📅 Current Date",
                    value=HISTORICAL_CUTOFF.date(),
                    min_value=HISTORICAL_CUTOFF.date(),
                    max_value=pd.Timestamp(
                        "2027-12-31"
                    ).date(),
                    key="region_forecast_date"
                )

            with c2:

                horizon = st.slider(
                    "🔮 Forecast Horizon (days)",
                    min_value=1,
                    max_value=477,
                    value=30,
                    step=1,
                    key="region_forecast_horizon"
                )

            st.info(
                "This forecast CSV contains Product_ID and "
                "Product_Name, but it does not contain "
                "Store_Location. Therefore, the forecast is "
                "displayed using product information."
            )

            if st.button(
                "🚀 Generate Forecast",
                type="primary",
                use_container_width=True,
                key="region_forecast_generate"
            ):

                start_date = (
                    pd.Timestamp(
                        current_date
                    )
                    + pd.Timedelta(days=1)
                )

                end_date = (
                    start_date
                    + pd.Timedelta(
                        days=int(horizon) - 1
                    )
                )

                result = region_data[
                    (
                        region_data[
                            "Forecast_Date"
                        ] >= start_date
                    )
                    &
                    (
                        region_data[
                            "Forecast_Date"
                        ] <= end_date
                    )
                ].copy()

                result = result.sort_values(
                    "Forecast_Date"
                )

                if result.empty:

                    st.warning(
                        "No forecast is available "
                        "for the selected date range."
                    )

                else:

                    total_prediction = (
                        result[
                            "Predicted_Units_Sold"
                        ].sum()
                    )

                    average_prediction = (
                        result[
                            "Predicted_Units_Sold"
                        ].mean()
                    )

                    minimum_prediction = (
                        result[
                            "Predicted_Units_Sold"
                        ].min()
                    )

                    maximum_prediction = (
                        result[
                            "Predicted_Units_Sold"
                        ].max()
                    )

                    c1, c2, c3, c4 = st.columns(4)

                    c1.metric(
                        "Total Forecast",
                        number(total_prediction)
                    )

                    c2.metric(
                        "Average Daily",
                        f"{average_prediction:,.1f}"
                    )

                    c3.metric(
                        "Minimum Daily",
                        number(minimum_prediction)
                    )

                    c4.metric(
                        "Maximum Daily",
                        number(maximum_prediction)
                    )

                    st.success(
                        "Forecast generated successfully."
                    )

                    st.subheader(
                        "Forecast Trend"
                    )

                    chart_data = (
                        result[
                            [
                                "Forecast_Date",
                                "Predicted_Units_Sold"
                            ]
                        ]
                        .set_index(
                            "Forecast_Date"
                        )
                    )

                    st.line_chart(
                        chart_data,
                        height=400
                    )

                    st.subheader(
                        "Region Forecast Data"
                    )

                    region_result = result[
                        [
                            "Forecast_Date",
                            "Product_ID",
                            "Product_Name",
                            "Predicted_Units_Sold"
                        ]
                    ].copy()

                    st.dataframe(
                        region_result,
                        use_container_width=True,
                        height=450,
                        hide_index=True
                    )

                    download_csv(
                        region_result,
                        "region_forecast.csv"
                    )

                    download_excel(
                        region_result,
                        "region_forecast.xlsx"
                    )
